require('catppuccin').setup {
  flavour = 'mocha',
  transparent_background = false,
  term_colors = false,
  dim_inactive = { enabled = false },
  styles = {
    keywords = { 'italic' },
    types = { 'italic' },
    conditionals = { 'italic' },
    loops = { 'italic' },
    comments = { 'italic' },
    functions = { 'bold' },
  },
  custom_highlights = function(colors)
    return {
      InclineNormal = { bg = colors.base },
      InclineNormalNC = { bg = colors.base },
      Pmenu = { bg = colors.base },
      Float = { bg = colors.base },
      FloatBorder = { bg = colors.base },
      NormalFloat = { bg = colors.base },
      ZenBg = { bg = colors.base },
      TreesitterContextLineNumber = { bg = colors.mantle },
      TreesitterContextBottom = { style = {} },
      TreesitterContextLineNumberBottom = { style = {} },
      CmpItemKindCopilot = { fg = colors.teal },
      ['@comment.note'] = { link = 'Comment' },
      ['@comment.todo'] = { link = 'Comment' },
      ['@comment.hint'] = { link = 'Comment' },
      ['@comment.info'] = { link = 'Comment' },
      ['@comment.error'] = { link = 'Comment' },
      ['@comment.warning'] = { link = 'Comment' },
    }
  end,
  integrations = {
    dap = true,
    dap_ui = true,
    blink_cmp = true,
    snacks = { enabled = true },
    flash = true,
    gitsigns = true,
    grug_far = true,
    illuminate = {
      enabled = true,
      lsp = true,
    },
    lsp_saga = true,
    lsp_trouble = true,
    markdown = true,
    mason = true,
    mini = {
      enabled = true,
      indentscope_color = 'overlay2',
    },
    native_lsp = {
      enabled = true,
      inlay_hints = { background = true },
    },
    navic = { enabled = true },
    neogit = true,
    neotest = true,
    noice = true,
    notify = true,
    octo = true,
    ufo = true,
    overseer = true,
    nvim_surround = true,
    rainbow_delimiters = true,
    treesitter = true,
    semantic_tokens = true,
    symbols_outline = true,
    which_key = true,
    treesitter_context = true,
    render_markdown = true,
  },
}
