require 'nyanvim.ui.snacks'
-- require 'nyanvim.ui.mini-indent'
require 'nyanvim.ui.indent'
require 'nyanvim.ui.highlight-colors'
require 'nyanvim.ui.notifications'
require 'nyanvim.ui.grapple'
require 'nyanvim.ui.modes'
require 'nyanvim.ui.folding'
require 'nyanvim.ui.colorful-winsep'
