require 'nyanvim.misc.mini'
require 'nyanvim.misc.mini-files'
require 'nyanvim.misc.session'
require 'nyanvim.misc.comment'
require 'nyanvim.misc.obsidian'
require 'nyanvim.misc.render-markdown'
require 'nyanvim.misc.search-replace'
